server:
  port: 8080

spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/reggie
      driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  config-location:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
reggie:
  path: /Users/cherish/Downloads/hh/

